name: Integration Tests and Artifact Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build application artifact
        run: zip -r application.zip ./*

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Initialize Packer
        run: packer init packer.pkr.hcl

      - name: Validate Packer Template
        run: | 
            packer validate packer.pkr.hcl
            packer fmt packer.pkr.hcl
            
      - name: Format Packer Template
        run: |
          if ! packer fmt -check -diff packer.pkr.hcl; then
            echo "Packer template is not properly formatted. Please run 'packer fmt' to format the template."
            exit 1
          fi